// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKuaxRhcsZy2qJCFKuCd6gsMAHZL4rdnQ',
    appId: '1:721598312784:web:6218de73d0ab29e24e7c55',
    messagingSenderId: '721598312784',
    projectId: 'afyadatabase-b2278',
    authDomain: 'afyadatabase-b2278.firebaseapp.com',
    storageBucket: 'afyadatabase-b2278.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL2Wt7dF7moOD29e_ElKX9enf9ZhJkqiU',
    appId: '1:721598312784:android:7930fd69ed4b6e934e7c55',
    messagingSenderId: '721598312784',
    projectId: 'afyadatabase-b2278',
    storageBucket: 'afyadatabase-b2278.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzbpUa0jPVNE3bW7TMQvKdO-JfXbzrZ9o',
    appId: '1:721598312784:ios:4e2b96270917b1fb4e7c55',
    messagingSenderId: '721598312784',
    projectId: 'afyadatabase-b2278',
    storageBucket: 'afyadatabase-b2278.appspot.com',
    iosBundleId: 'com.example.afyaChapchap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzbpUa0jPVNE3bW7TMQvKdO-JfXbzrZ9o',
    appId: '1:721598312784:ios:e386a5d32f83eb5f4e7c55',
    messagingSenderId: '721598312784',
    projectId: 'afyadatabase-b2278',
    storageBucket: 'afyadatabase-b2278.appspot.com',
    iosBundleId: 'com.example.afyaChapchap.RunnerTests',
  );
}
